[package]
name = "tenpai"
version = "0.0.1"
edition = "2021"


[[bin]]
name = "tenpai"
path = "src/main.rs"
test = false
bench = false

[dependencies]
tensorflow = { version = "0.21", features = ["tensorflow_gpu"] }
