// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gsxhnd/tenpai/tenhou/src/service"
)

// Injectors from wire.go:

func InitLog() *service.Log {
	log := service.NewLog()
	return log
}
